version: 2

jobs:
  build:
    docker:
      - image: openjdk:13.0.1-slim

    steps:
      - checkout

  test:
    docker:
      - image: openjdk:13.0.1-slim

    steps:
      - ./gradlew test

workflows:
  version: 2
  run:
    jobs:
      - build
      - test:
          requires:
            - build
